model_name : "google/gemma-7b-it"

# Fine-tuned model name
new_model : "gemma-7b-it_lora256"

wandb:
  project_name : 'gemma-7b-it'

dataset_name : 'gemma'
Train_args:
  per_device_train_batch_size : 8
  output_dir : "./checkpoints/gemma"
